brew install bash-completion
brew install dnsmasq
brew install gdbm
brew install git
brew install jq
brew install maven
brew install oniguruma
brew install openssl
brew install pip-completion
brew install python
brew install python3
brew install readline
brew install sqlite
brew install wget
brew install xz
